FORMAT: 1A
HOST: http://www.google.com

# ADMS
Devices API is a service similar to its physical paper presence on your table.

# Group Devices
Devices related resources of the **Devices API**

## Devices Collection [/devices?{sn}{name}{ip}{state}{productName}{pagination}{offset}]
### List Devices [GET]

+ Parameters
    + sn (optional, text, `1234`) ... Text `sn` of the desired device(s).
    + name (optional, text, `device_1`) ... Text `name` of the desired device(s).
    + ip (optional, text, `192.168.0.0`) ... Text `ip` of the desired device(s).
    + state (optional, number, `2`) ... Numeric `state` of the desired device(s).
    + productName (optional, text, `zkproduct`) ... Text `productName` of the desired device(s).
    + pagination (optional, number, `10`) ... Numeric `pagination` of the desired pagination size.
    + offset (optional, number, `0`) ... Numeric `offset` of the desired offset of the pagination.

+ Response 200 (application/json)

        [{ "sn": "1234", "name": "device", "ip": "192.168.0.0", "state": 2, "productName": "myProduct", "userCount": 2, "fingerPrintCount": 3, "transactionCount": 12}
        , { "sn": "12345", "name": "device2", "ip": "192.168.10.0", "state": 1, "productName": "myProduct2", "userCount": 12, "fingerPrintCount": 13, "transactionCount": 11}
        ]

### Create a Device [POST]
#### state allowed values: DvcSttsA (Active) - DvcSttsI (Inactive) - DvcSttsC (Connected) - DvcSttsD (Disconnected)
#### error codes will be either: a) missing mndatory field (SN or IP) b) duplicate entry (SN or IP) c) IP format is wrong
+ Request (application/json)

        { "sn": "1234", "name": "device", "ip": "192.168.0.0"}
        
+ Response 201 (application/json)

        { "id": 3, "state": "DvcSttsD" }
        
+ Response 400 (application/json)

        [{ "errorCode": "3" }, { "errorCode": "6" }]

## Device [/devices/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Show/Retrieve a Device [GET]
+ Response 200 (application/json)

    + Body

            { "sn": "1234", "name": "device", "ip": "192.168.0.0", "state": 2, "productName": "myProduct", "userCount": 2, "fingerPrintCount": 3, "transactionCount": 12}
        

### Remove a Device [DELETE]
+ Response 204

+ Response 400 (application/json)

        { "errorCode": "6" }
        
### Update a Device [POST]
#### state allowed values: DvcSttsA (Active) - DvcSttsI (Inactive) - DvcSttsC (Connected) - DvcSttsD (Disconnected)
#### error codes will be either: a) missing mndatory field (SN or IP) b) duplicate entry (SN or IP) c) IP format is wrong  d) invalid id
+ Request (application/json)

        { "sn": "1234", "name": "device", "ip": "192.168.0.0", "state": 2, "productName": "myProduct", "userCount": 2, "fingerPrintCount": 3, "transactionCount": 12}
        
+ Response 200 
        
+ Response 400 (application/json)

        [{ "errorCode": "3" }, { "errorCode": "6" }]